# Generated by Django 5.0.4 on 2024-05-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(auto_created=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('lessor_id', models.IntegerField(auto_created=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(auto_created=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('genre', models.CharField(max_length=64)),
                ('no_of_seats', models.IntegerField(max_length=8)),
                ('model', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('mileage', models.FloatField(max_length=64)),
                ('transmission', models.CharField(max_length=50)),
                ('no_of_doors', models.IntegerField(max_length=8)),
                ('fuel_policy', models.CharField(max_length=50)),
                ('price_per_day', models.IntegerField(max_length=64)),
                ('lessor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.lessor')),
            ],
        ),
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('rent_id', models.IntegerField(auto_created=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrental.customer')),
                ('vehicle_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrental.vehicle')),
            ],
        ),
    ]
