# Generated by Django 5.0.4 on 2024-05-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0003_alter_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
    ]
