# Generated by Django 5.0.4 on 2024-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0004_remove_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='path/'),
        ),
    ]
