# Generated by Django 5.0.4 on 2024-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0009_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
