# Generated by Django 5.0.4 on 2024-05-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0015_rename_customer_id_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrental.customer'),
        ),
        migrations.DeleteModel(
            name='Renting',
        ),
    ]
